spring:
  cloud:
    gcp:
      project-id: screen-golf-5e7e4
      credentials:
        location: classpath:smart-booking-google.json
      config:
        project-id: screen-golf-5e7e4
        credentials:
          location: classpath:smart-booking-google.json

  application:
    name: smart-booking-api

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.postgresql.Driver
      pool-name: HikariCP4Master
      jdbc-url: jdbc:postgresql://${DB_JDBC_URL}/${DB_DATABASE}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      auto-commit: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0.0.0
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  jwt:
    secret: ${JWT_SECRET}

  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # 또는 '*' 로 전부 노출 가능
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true

server:
  port: 8080

secret:
  key: ${AES_SECRET_KEY}
  iv: ${AES_SECRET_IV}


external:
  kakao-rest-api-key: ${EXTERNAL_KAKAO_API_KEY}
  openapi-rest-api-key: ${EXTERNAL_OPENAPI_KEY}
  sms:
    from: ${EXTERNAL_SMS_FROM}
    key: ${EXTERNAL_SMS_KEY}
    secret: ${EXTERNAL_SMS_SECRET}
    endpoint: ${EXTERNAL_SMS_ENDPOINT}

logging:
  level:
    org.flywaydb: DEBUG