spring:
  cloud:
    gcp:
      project-id: screen-golf-5e7e4
      credentials:
        location: classpath:smart-booking-google.json
      config:
        project-id: screen-golf-5e7e4
        credentials:
          location: classpath:smart-booking-google.json

  application:
    name: smart-booking-api

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
  jwt:
    secret: smartbookingsystem2024smartbookingsystem2024

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true

server:
  port: 8080

external:
  kakao-rest-api-key: '18aba9ac1f406cb303b93d2a03a5bbd3'
  openapi-rest-api-key: 'vFsA8BSDXJ%2FFR79%2By6MfZU9ejxyLYtruz9Ms%2F7dbjKXMuYbOFvi1Du0HsUWutw1VRgtEaSAD%2F8h9TFWANic3aw%3D%3D'
  sms:
    from: "1544-9971"
    key: "NCSEQVFDLTFVMSIR"
    secret: "LD6JAHNQG4XOXYIQ3YT1IDYVODITQNGA"
    endpoint: "https://api.coolsms.co.kr"
